### ISSUE TITLE
Please consider adding explicit license to ObjectExporter

### ISSUE THREAD

**Issue by obscurerichard** [OmarElabd/ObjectExporter#42]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://github.com/intel352/vagrant-shell-scripts/blob/master/LICENSE.md

(replace the copyright statement with your copyright, of course)

**Comment by OmarElabd** [comment]
Hi @obscurerichard. This is actually something I started to look into, I'm not very familiar with Open Source licensing so I just started to investigate the different licensing types. I really appreciate the request, once i'm better versed in the different open source licenses i'll definitely set one that makes sense for this project. If you have any suggestions for a license or have any resources you think i'd find useful please feel free to post here.

**Comment by obscurerichard** [comment]
Sure. Start here:

http://choosealicense.com/

Then read up on:

https://opensource.com/law/13/1/which-open-source-software-license-should-i-use

Then read the Open Source FAQ:

http://opensource.org/faq

Once you're done with that, I hope that you will choose a permissive license such as [the MIT license](http://opensource.org/licenses/MIT).

**Comment by neshmonin** [comment]
Hi Omar,
You use Scintilla in your product, so you may consider to licence your product similarly, e.g.:
----------------------
Copyright-2015 by Omar Elabd

All Rights Reserved 

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that 
both that copyright notice and this permission notice appear in 
supporting documentation. 

OMAR ELABD DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS 
SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY 
AND FITNESS, IN NO EVENT SHALL OMAR ELABD BE LIABLE FOR ANY 
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, 
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER 
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE 
OR PERFORMANCE OF THIS SOFTWARE.

**Comment by obscurerichard** [comment]
The Scintilla license suggested above looks very similar to me to the MIT license, though reworded. If it were my decision I'd go with the MIT license as it is widespread and well understood. If in doubt, consult your counsel, as I'm not a lawyer, and this is not legal advice :)

**Comment by neshmonin** [comment]
Dear Omar,
I joined this request because I'm considering to recommend your ObjectExporter for use in my team. However, since you have no assigned license, the product must be treated as copyrighted.
Please let me know if you are considering to grant no distribution rights to the product - so I'll be looking into some alternatives.

Thanks,

Alexander ;o)

P.S.: I'd also recommend you to issue at least a disclaimer, so you would not be legally responsible for any damage your product may produce to your users.

**Comment by OmarElabd** [comment]
@neshmonin are you planning on extending the software or do you simply wish to use the software as is on your team? If you wish to use it as is, then via the visual studio gallery that grants you the right to use it for commercial or non-commercial purposes. If you wish to extend and use it distribute it that is fine too, the only thing i'm still in consideration about is whether it would be ok to distribute and charge for it.

So if you don't plan to sell it to anyone at the moment you should be able to use it for your team without any issues. Regarding commercial distribution, I should probably have an answer for you after the Christmas break when i have some time to think about it and do some research. If you do need an answer before then please let me know.

**Comment by kwhitefoot** [comment]
Have you decided on a licence yet?  My personal preference is for GPL3 so that anyone using it commercially would be required to provide their bug fixes and improvements.  But really it just has to _have _a licence.  If you don't specify a licence then a lot  of people, especially those who might want to incorporate it in their own commercial application, will be reluctant to contribute because it will be unclear what their rights and duties are.  Corporate lawyers worry about this sort of thing.

**Comment by OmarElabd** [comment]
@kwhitefoot I've taken your suggestion and licensed the code under GPL3. It was something I was leaning towards. Hopefully this makes things a lot easier for anyone wanting to use the code.
