### ISSUE TITLE
VS2013 cannot build the solution with "incompatible" message.

### ISSUE THREAD

**Issue by constructor-igor** [OmarElabd/ObjectExporter#53]
VS2013 cannot build the solution with "incompatible" message.
Please, could you help to solve the issue?

![image](https://cloud.githubusercontent.com/assets/1849690/13641969/4858af78-e623-11e5-84c8-f8e34d9de77b.png)

**Comment by OmarElabd** [comment]
Hey @constructor-igor, i updated the VsPackage project to Visual Studio 2015 a while back. I'm not sure what the best way to open it in 2013 would be, since it's a one way upgrade. You can try editing the .csproj file and setting the .NET version to 4.5, or you can try to make a new Visual Studio Package project and copy all the files to that project.

**Comment by constructor-igor** [comment]
understood.
Changed attribute **MinimumVisualStudioVersion**
In any case, solution contains new features of c#, like this
```c#
e.Item.Text = $"{expressionName} (calculating...)";
```
and VS2013 cannot compile them.

![image](https://cloud.githubusercontent.com/assets/1849690/13646836/fe56923e-e639-11e5-882e-95c43db5dd38.png)

in any case, thank you for your fast response.
